version: '2'

services:
  nginx:
    image: prooph/nginx:www
    ports:
      - 8080:80
      - 443:443
    links:
      - php:php
    volumes:
      - .:/var/www

  php:
    image: prooph/php:7.1-fpm
    volumes:
      - .:/var/www
    env_file:
      - ./app.env

  aggregate_projection:
      image: prooph/php:7.1-cli
      volumes:
        - .:/app
      depends_on:
        - postgres
        - mongodb
      command: php /app/bin/aggregate_projection.php
      # Needed so that projection is automatically restarted when new events are registered in event machine
      # which are not yet known in the long-running projection process, see https://github.com/proophsoftware/event-machine-skeleton/issues/3
      restart: on-failure
      env_file:
        - ./app.env

  rabbit:
    image: prooph/rabbitmq
    ports:
      - 8081:15671
      - 15691:15691
    volumes:
      - ./env/rabbit/broker_definitions.json:/opt/definitions.json:ro
      - ./env/rabbit/rabbitmq.config:/etc/rabbitmq/rabbitmq-prooph.config

  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=identity_mgmt
    volumes:
      - ./env/postgres/initdb.d:/docker-entrypoint-initdb.d:ro
      - data-postgres:/var/lib/postgresql/data

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - data-mongodb:/data/db


#
# [ volumes definition ]
#
# creates Docker volumes which can be mounted by other containers too e.g. for backup
#
volumes:
  data-postgres:
    driver: local
  data-mongodb:
    driver: local